version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.redisson:redisson
    versions:
    - 3.15.1
    - 3.15.2
    - 3.15.3
  - dependency-name: org.apache.tomcat:tomcat-servlet-api
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: org.eclipse.jetty:jetty-maven-plugin
    versions:
    - 11.0.0
    - 11.0.1
